### ISSUE TITLE
Please setup github.io for live viewing of the spec

### ISSUE THREAD

**Issue by behdad** [Monotype/OpenType_Table_Source#1]
You need to create a gh_pages branch I believe.  Or better, create gh_pages branch, make it default, then remove master branch.

**Comment by behdad** [comment]
Doing so, the spec will become live at http://monotype.github.io/OpenType_Table_Source/

**Comment by taylorb-monotype** [comment]
Done.

**Comment by behdad** [comment]
Great.  Thanks!

**Comment by behdad** [comment]
Might want to update the README.md file to point to the live URL as well.

**Comment by taylorb-monotype** [comment]
Thanks. Done.
