### ISSUE TITLE
Document cmap syntax

### ISSUE THREAD

**Issue by brawer** [Monotype/OpenType_Table_Source#10]
Could the syntax for `*.cmap.txt` files be documented in the [specification](http://monotype.github.io/OpenType_Table_Source/otl_source.html)? For example, the format of [this file](https://github.com/googlei18n/noto-source/blob/master/src/NotoSansDevanagari/NotoSansDevanagariUI.cmap.txt). Also, it would be great to know if the format allows defining `cmap` tables of format 14 to support Unicode variation sequences.

**Comment by taylorb-monotype** [comment]
Added documentation for cmap source along with an example. This format does not support format 14 subtables.

**Comment by brawer** [comment]
Thank you!
