### ISSUE TITLE
chained-glyph.txt has typos

### ISSUE THREAD

**Issue by behdad** [Monotype/OpenType_Table_Source#13]
The chain sequence are missing a tab.  As such, the actions are treated as lookahead.

When adding the missing tab, then the file is not self-contained anymore since lookup u2aelow-sinh does not exist.

**Comment by behdad** [comment]
I've fixed my implementation to accept empty lookups (which are perfectly valid), so now I can declare lookups simply by:
```
lookup u2aelow-sinh    single
lookup end
```
and that's valid for both GSUB and GPOS.  It's trivial making tests self-contained this way.  Same thing for https://github.com/Monotype/OpenType_Table_Source/issues/12

**Comment by taylorb-monotype** [comment]
Typo was fixed in chained-glyph.txt. The file itself is not intended to be a self-contained test; it's intended to be an example for how to write a chained-glyph contextual lookup.
