### ISSUE TITLE
Reduce size of samples

### ISSUE THREAD

**Issue by behdad** [Monotype/OpenType_Table_Source#8]
Most are tiny, but a few are ~10k.  Would be nice to reduce them to illustrative sizes.

I like to use these files in fonttools as test data, and prefer to copy them intact as opposed to minimizing the bigger ones.

I can send a PR if that's desirable.

**Comment by JelleBosmaMT** [comment]
What is a PR?

**Comment by behdad** [comment]
> What is a PR?

A Pull-Request.  Github's way of submitting patches.

**Comment by taylorb-monotype** [comment]
We have these and will try to get them in place later today.

**Comment by behdad** [comment]
Thank you.

**Comment by taylorb-monotype** [comment]
Addressed in 9651c523a0d08a2da33eccd04211981e65c1e012

**Comment by behdad** [comment]
Thank you Bob.
